Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [5]:
N = 10
array = np.arange(N-1, -1, -1)
array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [6]:
diag_ = np.diag(array, k=0)
diag_

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
diag_sum = 0

for i in range(0, 10):
    for el in diag_:
        diag_sum += el[i]

diag_sum

45

Задание 3
Решите систему уравнений

In [ ]:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [22]:
from numpy import linalg

In [23]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [5, 0, 4] ] )

In [24]:
b = np.array( [4, 12, -3] )

In [25]:
linalg.solve(a, b)

array([-1.56,  4.52,  1.2 ])

In [26]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

Задача 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем

In [28]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [29]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [36]:
cosine = []
next_user_length = np.linalg.norm(next_user_stats)

for user in users_stats:
    user_length = np.linalg.norm(user)
    user_cosine = np.dot(next_user_stats, user) / (next_user_length * user_length)
    cosine.append(user_cosine)

print(f'Самый схожий пользователь: {cosine.index(max(cosine)) + 1}')

Самый схожий пользователь: 8
